# Generated by Django 3.1.6 on 2021-02-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='posologiaMedicamento',
            field=models.IntegerField(),
        ),
    ]
