# Generated by Django 3.1.6 on 2021-02-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=100)),
                ('nomeMedico', models.CharField(max_length=100)),
                ('DiaHorario', models.DateTimeField()),
            ],
        ),
    ]
