# Generated by Django 3.1.6 on 2021-02-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='dia',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.DateTimeField(),
        ),
    ]
